name: Build Only

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-only:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # This build step does not need secrets
    # and can therefore be executed from any fork
    - name: Build only
      run: mvn -B clean install -DskipTests
