name: Release to Maven Central

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        server-id: central
        server-username: ${{ vars.CENTRAL_TOKEN_USERNAME }}
        server-password: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Set up Maven settings.xml
      uses: s4u/maven-settings-action@v2
      with:
        servers: |
          [{
            "id": "central",
            "username": "${{ vars.CENTRAL_TOKEN_USERNAME }}",
            "password": "${{ secrets.CENTRAL_TOKEN_PASSWORD }}"
          }]
        gpg: true

    - name: Run Maven Release
      run: mvn -Prelease-sign-artifacts -DskipTests -Darguments=-DskipTests release:prepare release:perform -B
      env:
        GPG_TTY: $(tty)
