name: Release to Maven Central

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        server-id: central
        server-username: ${{ vars.CENTRAL_TOKEN_USERNAME }}
        server-password: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config credential.helper 'store --file ~/.git-credentials'
        echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

    - name: Set up Maven settings.xml
      uses: s4u/maven-settings-action@v2
      with:
        servers: |
          [{
            "id": "central",
            "username": "${{ vars.CENTRAL_TOKEN_USERNAME }}",
            "password": "${{ secrets.CENTRAL_TOKEN_PASSWORD }}"
          }]
        gpg: true

    - name: Run Maven Release
      run: mvn -Prelease-sign-artifacts -DskipTests -Darguments=-DskipTests -DtagNameFormat="v@{project.version}" release:prepare release:perform -B
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
